rvm: 3.1.3
addons:
  postgresql: "9.5"
services:
  - postgresql

cache: bundler
before_install:
  - docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.17.7
  - sleep 5

before_script:
  - timeout 30 sh -c 'until nc -z $0 $1; do sleep 1; done' localhost 9200
  - bundle exec rails db:create
  - bundle exec rails db:migrate

script:
  - curl http://localhost:9200/_cluster/health?pretty
  - bundle exec rspec
