language: ruby
ruby: 3.1.3
addons:
  postgresql: "9.5"
services:
  - postgresql
  - elasticsearch

before_install:
  - sleep 10

before_script:
  - timeout 30 sh -c 'until nc -z $0 $1; do sleep 1; done' localhost 9200
  - bundle exec rails db:create
  - bundle exec rails db:migrate

script:
  - curl http://localhost:9200/_cluster/health?pretty
